### ISSUE TITLE
Using QBImagePicker with swift

### ISSUE THREAD

**Issue by Tom-Fox1** [questbeat/QBImagePicker#117]
I am trying to use this library within a swift project and I do not want to have to write objective. Below is what I have so far

    @IBAction func PickTimeLpase(sender: AnyObject) {
    
        let ipc = QBImagePickerController()
        ipc.showsNumberOfSelectedAssets = true
        
        presentViewController(ipc, animated: true, completion: nil)
    }

I only want user to be able to choose time lapses and nothing else, can some one tell me the code to use to achieve this? 

Also once the user has picked a time lapse how exactly do I then get access to the time lapse file so I can display it

Thanks in advance!

**Comment by questbeat** [comment]
You can change which albums to be shown by modifying `assetCollectionSubtypes` property of `QBImagePickerController`.
In that case you should specify `PHAssetCollectionSubtypeSmartAlbumTimelapses` (`.SmartAlbumTimelapses` in Swift).

> Also once the user has picked a time lapse how exactly do I then get access to the time lapse file so I can display it

What you will get are the `PHAsset` instances, so you can use `PHImageManager` to access to it.
(Maybe [this](http://stackoverflow.com/questions/33858270/getting-url-for-phasset) is helpful.)

**Comment by Tom-Fox1** [comment]
Ok thank you
