### ISSUE TITLE
PhotoKit iphone Device on iPad Run,  Could not display

### ISSUE THREAD

**Issue by sujiewen** [questbeat/QBImagePicker#170]
PhotoKit iphone Device on iPad Run,  Could not display。
<img width="661" alt="0a4a4839-7644-422e-8c88-0956307826a1" src="https://cloud.githubusercontent.com/assets/1973318/16911896/b75f091a-4d13-11e6-94b3-c2ae453635bc.png">
<img width="566" alt="2016-07-18 18 16 39" src="https://cloud.githubusercontent.com/assets/1973318/16911926/eaa8ce00-4d13-11e6-86e1-9cb8282d5e98.png">

**Comment by sujiewen** [comment]
https://forums.developer.apple.com/thread/43400

**Comment by javaboyjunior** [comment]
I have a solution of sorts, will make a pull request in a few.

It seems the result handler for requestImageForAsset gets called twice, the second time with a nil result. Therefore code like cell.imageView3.image sets the cell's image to nil.

I just added a null check in all the places requestImageForAsset is called, for example:

if (cell.tag == indexPath.row && result != nil) {
                                     cell.imageView3.image = result;
                                 }

And all is now well.

**Comment by javaboyjunior** [comment]
It's already in this pull request:

https://github.com/questbeat/QBImagePicker/pull/153/commits/df3a6538dc8be1756e9774336248d72f48f9d759

**Comment by sujiewen** [comment]
Thank you!
