### ISSUE TITLE
iOS8 - Deleted Images function creates NSRangeException when selecting Camera Roll

### ISSUE THREAD

**Issue by maddoggy1979** [questbeat/QBImagePicker#28]
I'm getting this NSRangeException (and the app locks up) when I use the QBImagePicker and select my Camera Roll.
```*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 28 beyond bounds [0 .. 27]'```

When I select Camera Roll in my QBImagePicker, this exception is raised and the app stops responding.

They symptoms & cause of the issue are below:
- in QBImagePicker, the Camera Roll row says there are 37 images.
- In my actual camera roll, there are only 28 images, + 9 in the Recently Deleted 'album' (which totals 37)
- So, because the picker is looking for 37 images, but in the album proper there are only 28, that relates directly to the NSRangeException.
- If I go and 'Delete All' from the Recently Deleted album, the issue is resolved.

Once again, Apple have gone and stuffed it - those Deleted Photos really shouldn't be counted in a normal API call to get the Photo Album, but hey... here we are, and it'll need a bit of a workaround maybe.

Thanks (great controller by the way).

**Comment by questbeat** [comment]
I think this problem has solved.
