### ISSUE TITLE
ios 8 crash when launching image picker

### ISSUE THREAD

**Issue by reggiea** [questbeat/QBImagePicker#31]
Hi,

Been using your controller and works great in ios 7. In ios 8 same code the image picker always crashes before loading the photo albums:

2014-08-07 18:53:00.082 MYAPP[817:434075] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayI objectAtIndex:]: index 0 beyond bounds for empty array'
*** First throw call stack:
(0x2be89e2f 0x38f2ac8b 0x2bd9ee8d 0x54d3b 0x2f500251 0x2eede795 0x2eec81f3 0x2efaaf69 0x2eec79d1 0x2eec7681 0x2eeabb51 0x2eeab815 0x2eeab1f1 0x2eeaaff5 0x2eea4ecd 0x2be505bd 0x2be4dc7b 0x2be4e083 0x2bd9c611 0x2bd9c423 0x332f60a9 0x2f4e6485 0x2ea6d 0x394b0aaf)
libc++abi.dylib: terminating with uncaught exception of type NSException

Appears to be QBImagePickerThumbnailView crashing around this point:

    UIImage *thumbnailImage = [self.thumbnailImages objectAtIndex:0];
    
    CGRect thumbnailImageRect = CGRectMake(0, 4.0, 70.0, 70.0);
    CGContextFillRect(context, thumbnailImageRect);
    [thumbnailImage drawInRect:CGRectInset(thumbnailImageRect, 0.5, 0.5)];

The last issue posted mentions due to the Recently Deleted album introduced in ios 8, but I tried after emptying this album and it still crashes. Any ideas? Thanks!

ra

**Comment by questbeat** [comment]
I think this problem has solved.
