### ISSUE TITLE
Launching DemoApp crash in ios7 and ios8

### ISSUE THREAD

**Issue by eugeniobaglieri** [questbeat/QBImagePicker#40]
Launching demo, when select an album the app crash with this error:
** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSPlaceholderString initWithFormat:locale:arguments:]: nil argument'
*** First throw call stack:

the line that cause error is:

footerView.textLabel.text = [NSString stringWithFormat:NSLocalizedStringFromTableInBundle(format,
                                                                                                          @"QBImagePickerController",
                                                                                                          [NSBundle bundleWithPath:[[NSBundle mainBundle] pathForResource:@"QBImagePickerController" ofType:@"bundle"]],
                                                                                                          nil),

The returned bundle is always nil

**Comment by questbeat** [comment]
Fixed in [2.2.3](https://github.com/questbeat/QBImagePicker/tree/2.2.3).
