### ISSUE TITLE
Crash with Photo Stream on iOS 8.1

### ISSUE THREAD

**Issue by anasb** [questbeat/QBImagePicker#41]
Selecting images from Photo Stream on iOS 8.1 crashes because assetForURL:resultBlock:failureBlock: always returns a nil asset in that case.

Same as here: http://stackoverflow.com/questions/26480526/alassetslibrary-assetforurl-always-returning-nil-for-photos-in-my-photo-stream

**Comment by questbeat** [comment]
Fixed in [2.2.4](https://github.com/questbeat/QBImagePicker/tree/2.2.4).
