### ISSUE TITLE
Crashes if there is no Asset in folder

### ISSUE THREAD

**Issue by reeyan** [questbeat/QBImagePicker#55]
Hi 
First of all, thanks for the wonderful artifact. 
I observed on issue on iOS8.3 SDK, Probably previous version of SDK.
If there is no asset in folder(Album), line 373 in QBAssetsViewController.m throws an exception.
It tries to access an item that does not exist. PHFetchResult contains nothing.

**Comment by questbeat** [comment]
Hi, thank you for your report.
I've just updated.
Please try the version `3.1.1`.

**Comment by reeyan** [comment]
Yes.. it is fixed.. Thank you so much for your response.
