### ISSUE TITLE
Installed via CocoaPods, stuck in Japanese

### ISSUE THREAD

**Issue by tspangler** [questbeat/QBImagePicker#58]
I've installed v2.5.1 through CocoaPods, since my app needs to support iOS 7. Now, whenever I display the picker, the title is always アルバム. My project is all-English and does not have any kind of i18n code in it.

I did have a Japanese keyboard added in Settings, which I removed, and the issue continues. It also happens on the simulator.

How can I force `QBImagePickerController` to display only in English?

よろしくお願いします。😀

**Comment by DrakeW** [comment]
I had the same problem lol, how should I fix it? XD

**Comment by DrakeW** [comment]
Hey I just found the solution, so in QBImagePicker, you can find the two folders named "Base.lproj" and "ja.lproj", and inside both folders there is a string file. So basically just copy the content of the string file in the Base.lproj to that of ja.lproj, and it works like a charm :+1:

**Comment by questbeat** [comment]
@tspangler 
I've just fixed and release [2.5.2](https://github.com/questbeat/QBImagePicker/releases/tag/2.5.2).
Please try it.

**Comment by questbeat** [comment]
@DrakeW 

> So basically just copy the content of the string file in the Base.lproj to that of ja.lproj, and it works like a char

It's not a solution.
You should rename `Base.lproj` to `en.lproj`.

**Comment by tspangler** [comment]
@questbeat Fixed in 2.5.2. Thank you!

**Comment by ashishterp** [comment]
I'm having this issue using cocoapods on 3.2.0

**Comment by lossefanya** [comment]
I had same issue with 3.2.0(cocoapod). So I've manually added source code to project. And it solved the problem.
