### ISSUE TITLE
How can i remove a selected asset by program?

### ISSUE THREAD

**Issue by GreatFireWall** [questbeat/QBImagePicker#59]
I use a collectionView to show what the asset user selected. when user tap the cell in collectionView, i want to unselected a asset in QBImagePicker.  At now, i open QBImagePicker,  previous selected asset is always selected if you never touch it in QBImagePicker.

**Comment by questbeat** [comment]
You should re-create `QBImagePickerController` instance every time you show the picker.
But then the selection will be lost.
So if you can set `selectedAssetURLs`, your problem will be solved, right?

**Comment by GreatFireWall** [comment]
ok, thank you .
