### ISSUE TITLE
How to get selected video file's absolute path

### ISSUE THREAD

**Issue by Thavasidurai** [questbeat/QBImagePicker#6]
I am trying to use this control in my app, In my app i have to upload the selected videos and images to server. when uploading images there is no problem because i can get the raw image from didFinishPickingMediaWithInfo delegate method so i will save that raw image in a particular path then i will send that path to server. But when i am trying upload video file i am facing problem because it does not return uiimagepickercontrollermediaurl. How can i get the file path of selceted video file? Please guide me

**Comment by leasontou** [comment]
I have this problem too,and what is infoDic?the delegate method doesn't have this param.Can you help me?
