### ISSUE TITLE
Not sorting photos exactly like native photoapp

### ISSUE THREAD

**Issue by knutigro** [questbeat/QBImagePicker#79]
I have noticed that QBImagePicker not has exactly same sorting as in the native iOS photoapp.

Lets say I edit a photo in Camera+ app and save it back to gallery.
In the native photopicker the photo I edited and saved will be down at the bottom since it was the last one I changed. The original will be at its original place according to its creation date.

In QBImagePicker the photo I edited will be just after at it's original according to it's original creation date.

**Comment by ataranlen** [comment]
I think a Better solution would be to fix the code that is supposed to scroll to the bottom.

https://github.com/questbeat/QBImagePicker/blob/master/QBImagePicker/QBAssetsViewController.m#L106-L111

**Comment by ataranlen** [comment]
I was able to fix it on my end with the following code: 
```
 // Scroll to bottom
    if (self.fetchResult.count > 0 && self.isMovingToParentViewController && !self.disableScrollToBottom) {
        NSIndexPath *indexPath = [NSIndexPath indexPathForItem:(self.fetchResult.count - 1) inSection:0];
        [self performSelector:@selector(scrollToIndexPath:) withObject:indexPath afterDelay:0.0f];
    }
}

- (void)scrollToIndexPath:(NSIndexPath*)indexPath
{
    [self.collectionView scrollToItemAtIndexPath:indexPath atScrollPosition:UICollectionViewScrollPositionTop animated:NO];
}
```
Not sure why the original code was no longer working, Apple must have changed something.

**Comment by knutigro** [comment]
hmm.. this issue is not about the scrolling to the bottom, it's about the sorting of the photos and I tracked the problem to this line:

`options.sortDescriptors = @[[NSSortDescriptor sortDescriptorWithKey:@"creationDate" ascending:YES]];` 

My suggestion is to remove this line of code, which will result in the default and original behaviour of fetches from `PHAssetCollection`. The default sorting is by the way also done by "creationDate", but with some small differences to what happens when you add this manually. 

Probably the fix you suggest @ataranlen  is also good, but in my opionion it's another issue.

**Comment by maeji** [comment]
in 2.5.2 I changed like that in QBAssetViewController,
``` Objective-C
// Scroll to bottom
    if (self.numberOfAssets > 0 && self.isMovingToParentViewController && !self.disableScrollToBottom) {
        NSIndexPath *indexPath = [NSIndexPath indexPathForItem:(self.numberOfAssets - 1) inSection:0];
        dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0.0 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
            [self.collectionView scrollToItemAtIndexPath:indexPath atScrollPosition:UICollectionViewScrollPositionTop animated:NO];
        });
    }
```
It work! :-)

**Comment by knutigro** [comment]
This issue is still not about scrolling. It's about sorting. The order of the images. It has a very simple fix which I have proposed, by removing one line of code which is not needed and adds artificial behaviour.

**Comment by questbeat** [comment]
#80 was merged.
