### ISSUE TITLE
add new simplified Chinese into Pods>QBImagePickerController>Resources, app crash

### ISSUE THREAD

**Issue by AngleZhou** [questbeat/QBImagePicker#87]
I need to localize the language into simplified Chinese. And I did the following:
1. Clone the repo down on local disk, and it's already been localized and contains a zh-Hans.lproj folder.
2. I copied the folder into Pods project > Pods > QBImagePickerController > Resources. It appears in the catalog and also in the same folder as ja.lproj
3. Directly run the build on device, it works well.
4. Archive the build and download it from a webpage and install, it will crash when enter into imagePicker.

I cannot figure it out why it will crash. please help or give me some hints. Thanks!!

**Comment by AngleZhou** [comment]
I deleted all local files and reload the pod, and the crash is gone.

**Comment by Chren** [comment]
Hello, how do u finally get simplified Chinese localization working?
I add zh-Hans.lproj which contains QBImagePicker.strings for simplified Chinese to Pods project, but seems not working at all.
