### ISSUE TITLE
I want use pods, but there is a issues

### ISSUE THREAD

**Issue by LSsoftware** [questbeat/QBImagePicker#90]
I add pod "QBImagePickerController" 
error look like :
[!] The platform of the target `Pods` (iOS 7.0) is not compatible with `QBImagePickerController (3.2.0)` which has a minimum requirement of iOS 8.0.

This version QBImagePickerController (3.2.0) is not what I want.
I want 2.6.0     - -!

I recommend 
Version >= 3.0.0 using pod 'QBImagePickerControllerLatest'
Version < 3.0.0 using pod 'QBImagePickerController'

**Comment by LSsoftware** [comment]
and when i change podfile with
pod 'QBImagePickerController', '~> 2.6.0'

error look like : 
[!] Unable to satisfy the following requirements:

- `QBImagePickerController (~> 2.6.0)` required by `Podfile`

**Comment by neufeng** [comment]
Version 2.6.0 is not exist. Try pod 'QBImagePickerController', '~> 2.5.2', good luck!

**Comment by LSsoftware** [comment]
I know there's no 2.6.0, at that time I wanted a new version
